CREATE TABLE IF NOT EXISTS owned_assets (
    id          BIGSERIAL PRIMARY KEY NOT NULL,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    asset_id    BIGINT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    quantity    DOUBLE PRECISION NOT NULL,
    bought_for  DOUBLE PRECISION NOT NULL,
    bought_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
